### ISSUE TITLE
UI - Followers Modal (nostdiek1@gmail.com)

### ISSUE THREAD

**Issue by ZacChristensen31** [bradh43/curro#26]
XR: Looks good to me.
-Audrey

---
When viewing another person's followers/following, there is always "No Users Found" at the bottom of the list. Also, one time the list showed each person twice, but I could not replicate this behavior again.

---

No design needed. Remove the "no users found" option.

**Comment by ZacChristensen31** [comment]
This was raised by Nate, but I can confirm the double person thing happened to me as well. Not sure if this has been fixed somehow, will keep an eye out for it if it happens again.

**Comment by nathanostdiek** [comment]
Replicate this behavior by going to a team page, click members, and click a specific person. When viewing their followers/following the list appears twice (same person listed twice).
